branches:
  only:
  - development
language: python
cache: pip
python:
- 3.6
env:
- DJANGO='django>=2.1,<2.2'
- DJANGO=https://github.com/django/django/archive/master.tar.gz
matrix:
  include:
  - python: 3.7
    env: DJANGO='django>=2.1,<2.2'
    dist: xenial
  - python: 3.7
    env: DJANGO=https://github.com/django/django/archive/master.tar.gz
    dist: xenial
before_install:
- python -m pip install poetry
install:
- python -m pip install "$DJANGO"
- python -m pip install codecov
- poetry install -v
script:
- pytest
after_success:
- codecov
